packages:
  - 'apps/*'
  - 'packages/*'

catalog:
  typescript: 5.7.3
  '@types/node': ^22.10.2
  'autoprefixer': '^10.4.20'
  'eslint-config-next': '15.1.7'
  'postcss': '^8.5.3'
  'tailwindcss': '^3.4.1'
  # "@tailwindcss/postcss": "^4.0.8"
  'prettier': '^3.5.0'
  'turbo': '^2.4.4'
  '@turbo/gen': '^2.4.0'
  '@radix-ui/react-slot': '^1.1.2'
  'class-variance-authority': '^0.7.1'
  'clsx': '^2.1.1'
  'lucide-react': '^0.475.0'
  'tailwindcss-animate': '^1.0.7'
  'tailwind-merge': '^3.0.2'
  'eslint': '^9'
  'react-hook-form': '^7.54.2'

catalogs:
  react:
    'react': '^19.0.0'
    'react-dom': '^19.0.0'
    '@types/react': ^19
    '@types/react-dom': ^19
  nextjs:
    'next': '15.2.0'
  eslint-config:
    '@eslint/js': '^9.21.0'
    '@next/eslint-plugin-next': '^15.1.6'
    'eslint': '^9.21.0'
    'eslint-config-prettier': '^10.0.1'
    'eslint-plugin-only-warn': '^1.1.0'
    'eslint-plugin-react': '^7.37.4'
    'eslint-plugin-react-hooks': '^5.1.0'
    'eslint-plugin-turbo': '^2.4.0'
    'globals': '^15.15.0'
    'typescript-eslint': '^8.24.0'
